ShareMusic/Controllers/GroupsController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ShareMusic.Models.Groups;
using ShareMusic.Services.Interfaces;
using ShareMusic.Extensions;

namespace ShareMusic.Controllers
{
    [Authorize]
    public class GroupsController : Controller
    {
        private readonly IGroupsService groupsService;

        public GroupsController(IGroupsService groupsService)
        {
            this.groupsService = groupsService;
        }

        public IActionResult CreateGroup()
        {
            CreateGroupInputModel viewModel = new CreateGroupInputModel { MultiSelectUsers = this.groupsService.ListAllUsers() };
            return this.View(viewModel);
        }

        [HttpPost]
        public IActionResult CreateGroup(CreateGroupInputModel inputModel) 
        {
            if (!ModelState.IsValid)
            {
                inputModel.MultiSelectUsers = this.groupsService.ListAllUsers();
                return this.View(inputModel);
            }

            inputModel.OwnerId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            this.groupsService.CreateGroup(inputModel);

            return this.Redirect("List");
        }

        public IActionResult List() 
        {
            string userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            GroupsListViewModel viewModel = this.groupsService.ListAllGroupsForUser(userId);
            return this.View(viewModel);
        }

        public IActionResult Search(string searchText)
        {
            GroupsSearchResultViewModel viewModel = this.groupsService.SearchGroups(searchText);
            return this.View(viewModel);
        }

        public IActionResult Details(string id)
        {
            if (id.IsNullOrEmptyOrWhiteSpace())
            {
                return this.RedirectToAction("List");
            }

            string userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            GroupDetailsViewModel groupDetails = this.groupsService.GetGroupDetails(id, userId);
            return this.View(groupDetails);
        }

        [HttpPost]
        public IActionResult Details(UsersListViewComponentViewModel inputModel, string id)
        {
            if (!ModelState.IsValid)
            {
                string userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
                GroupDetailsViewModel groupDetails = this.groupsService.GetGroupDetails(id, userId);
                return this.View(groupDetails);
            }

            this.groupsService.AddUsers(inputModel, id);
            return this.RedirectToAction("List");
        }

        [HttpPost]
        public IActionResult RemoveUser(string username, string groupId)
        {
            if (username.IsNullOrEmptyOrWhiteSpace() || groupId.IsNullOrEmptyOrWhiteSpace())
            {
                return this.RedirectToAction("List");
            }

            this.groupsService.RemoveUser(username, groupId);
            return this.RedirectToAction("Details", new { id = groupId });
        }

        [HttpPost]
        public IActionResult DeleteGroup(string groupName) 
        {
            if (groupName.IsNullOrEmptyOrWhiteSpace())
            {
                return RedirectToAction("List");
            }

            this.groupsService.DeleteGroup(groupName);

            return this.RedirectToAction("List");
        }

        [HttpPost]
        public IActionResult AddSong(string selectedGroup, int songId) 
        {
            if (selectedGroup.IsNullOrEmptyOrWhiteSpace() || songId <= 0)
            {
                return this.Redirect("/");
            }

            string groupId = this.groupsService.AddSong(selectedGroup, songId);
            return this.RedirectToAction("Details", new { id = groupId });
        }

        [HttpPost]
        public IActionResult RemoveSong(int songId, string groupName) 
        {
            if (groupName.IsNullOrEmptyOrWhiteSpace() || songId <= 0)
            {
                return this.RedirectToAction("List");
            }

            string groupId = this.groupsService.RemoveSong(songId, groupName);
            if (string.IsNullOrEmpty(groupId))
            {
                return this.RedirectToAction("List");
            }

            return this.RedirectToAction("Details", new { id = groupId });
        }
    }
}

ShareMusic/Controllers/SongsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ShareMusic.Common;
using ShareMusic.DataProviders.Interfaces;
using ShareMusic.Models.Songs;
using ShareMusic.Services.Interfaces;
using ShareMusic.Extensions;

namespace ShareMusic.Controllers
{
    public class SongsController : Controller
    {
        private readonly ISongsService songsService;
        private readonly IYoutubeDataProvider youtubeDataProvider;
        private readonly ISongAndArtistNamesSplitterService splitterService;
        private readonly ISongMetadataService metadataService;
        private readonly IGeniusLyricsDataProvider geniusLyrics;

        private readonly ILogger<SongsController> logger;

        public SongsController(
            ISongsService songsService,
            IYoutubeDataProvider youtubeDataProvider,
            ISongAndArtistNamesSplitterService splitterService,
            ISongMetadataService metadataService,
            IGeniusLyricsDataProvider geniusLyrics,
            ILogger<SongsController> logger)
        {
            this.songsService = songsService;
            this.youtubeDataProvider = youtubeDataProvider;
            this.splitterService = splitterService;
            this.metadataService = metadataService;
            this.geniusLyrics = geniusLyrics;
            this.logger = logger;
        }

        [Authorize]
        public IActionResult AddSong()
        {
            AddSongInputModel inputModel = new AddSongInputModel();
            return this.View(inputModel);
        }

        [Authorize]
        [HttpPost]
        public IActionResult AddSong(AddSongInputModel inputModel) 
        {
            if (!ModelState.IsValid)
            {
                return this.View(inputModel);
            }

            List<string> artists = this.splitterService.SplitArtistName(inputModel.Artist).ToList();
            int songId = this.songsService.CreateSong(inputModel.Song, artists);

            string videoId = this.youtubeDataProvider.SearchVideo(string.Join(" ", artists), inputModel.Song);
            if (!string.IsNullOrEmpty(videoId))
            {
                this.metadataService.AddMetadataInfo(songId, GlobalConstants.YouTubeVideo, videoId);
            }
            else
            {
                this.logger.LogWarning($"Video for {string.Join(" ", artists)} {inputModel.Song} not found");
            }

            string lyrics = this.geniusLyrics.AskForLyrics(inputModel.Song, string.Join(" ", artists));
            if (!string.IsNullOrEmpty(lyrics))
            {
                this.metadataService.AddMetadataInfo(songId, GlobalConstants.Lyrics, lyrics);
            }
            else
            {
                this.logger.LogWarning($"Lyrics for {string.Join(" ", artists)} {inputModel.Song} not found");
            }

            this.songsService.UpdateSongsSystemData(songId);

            return this.Redirect("/");
        }

        public IActionResult Details(int songId) 
        {
            if (songId <= 0)
            {
                return this.Redirect("/");
            }

            string userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            SongDetailsViewModel viewModel = this.songsService.GetDetails(songId, userId);
            return this.View(viewModel);
        }

        public IActionResult Search(string searchText) 
        {
            if (searchText.IsNullOrEmptyOrWhiteSpace())
            {
                return this.Redirect("/");
            }

            SongsSearchResultViewModel viewModel = this.songsService.Search(searchText);
            return this.View(viewModel);
        }
    }
}

ShareMusic/Views/Shared/_Footer.cshtml
<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2020 - ShareMusic - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>

ShareMusic/Views/Shared/_Header.cshtml
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Share Music</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <partial name="_LoginPartial" />
                <ul class="navbar-nav flex-grow-1">
                    @if (this.User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Songs" asp-action="AddSong">Add Song</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Groups" asp-action="List">Groups</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>

ShareMusic/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ShareMusic</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <asp:ContentPlaceHolder ID="MultiSelectContent" runat="server"></asp:ContentPlaceHolder>
</head>
<body>
    <partial name="_Header" />

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <partial name="_Footer" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

ShareMusic/Views/Shared/_LayoutUsersListViewComponent.cshtml
@RenderBody()
@RenderSection("Scripts", false)

ShareMusic/Views/Shared/_SongCardPartialView.cshtml
@model SongCardViewModel

<div>
    <a asp-controller="Songs" asp-action="Details" asp-route-songId="@Model.SongId">
        <img src="https://img.youtube.com/vi/@Model.VideoId/mqdefault.jpg" alt="@Model.Name" />
    </a>

    <div class="card-body">
        <p class="card-title">@Model.Name</p>
    </div>
</div>