ShareMusic/Models/GeniusLyricsDataProvider/Search/SearchLyricsModel.cs
namespace ShareMusic.Models.GeniusLyricsDataProvider.Search
{
    public class SearchLyricsModel
    {
        public Meta meta { get; set; }

        public Response response { get; set; }
    }

    public class Meta
    {
        public int status { get; set; }
    }

    public class Response
    {
        public Hit[] hits { get; set; }
    }

    public class Hit
    {
        public string type { get; set; }
        public Result result { get; set; }
    }

    public class Result
    {
        public string api_path { get; set; }

        public string lyrics_state { get; set; }

        public string title { get; set; }
    }
}

ShareMusic/Models/Groups/CreateGroupInputModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShareMusic.Attributes;

namespace ShareMusic.Models.Groups
{
    public class CreateGroupInputModel
    {
        [Required]
        [GroupNameValidation]
        [StringLength(40, ErrorMessage = "{0} must be between {1} and {2} characters", MinimumLength = 3)]
        public string Name { get; set; }

        [Display(Name = "Add users to group")]
        public MultiSelectList MultiSelectUsers { get; set; }

        public IEnumerable<string> SelectedUsers { get; set; }

        public string OwnerId { get; set; }
    }
}

ShareMusic/Models/Groups/GroupDetailsViewModel.cs
using System.Collections.Generic;

namespace ShareMusic.Models.Groups
{
    public class GroupDetailsViewModel
    {
        public string Id { get; set; }

        public string Name { get; set; }

        public string OwnerName { get; set; }

        public ICollection<string> GroupUserNames { get; set; }

        public ICollection<GroupSongsViewModel> Songs { get; set; }

        public bool IsUserInGroup { get; set; }
    }
}

ShareMusic/Models/Groups/GroupSongsViewModel.cs
namespace ShareMusic.Models.Groups
{
    public class GroupSongsViewModel
    {
        public int SongId { get; set; }

        public string Name { get; set; }
    }
}

ShareMusic/Models/Groups/GroupUsersListViewModel.cs
namespace ShareMusic.Models.Groups
{
    public class GroupUsersListViewModel
    {
        public string Id { get; set; }

        public string Name { get; set; }
    }
}

ShareMusic/Models/Groups/GroupsListViewModel.cs
using System.Collections.Generic;

namespace ShareMusic.Models.Groups
{
    public class GroupsListViewModel
    {
        public ICollection<GroupUsersListViewModel> GroupsForUser { get; set; }

        public ICollection<GroupsOwnedByUserViewModel> OwnedGroups { get; set; }

        public string SearchText { get; set; }
    }
}

ShareMusic/Models/Groups/GroupsOwnedByUserViewModel.cs
namespace ShareMusic.Models.Groups
{
    public class GroupsOwnedByUserViewModel
    {
        public string Id { get; set; }

        public string Name { get; set; }
    }
}

ShareMusic/Models/Groups/GroupsSearchResultListViewModel.cs
namespace ShareMusic.Models.Groups
{
    public class GroupsSearchResultListViewModel
    {
        public string Id { get; set; }

        public string Name { get; set; }
    }
}

ShareMusic/Models/Groups/GroupsSearchResultViewModel.cs
using System.Collections.Generic;

namespace ShareMusic.Models.Groups
{
    public class GroupsSearchResultViewModel
    {
        public int Count { get; set; }

        public ICollection<GroupsSearchResultListViewModel> SearchResults { get; set; }

        public string SearchText { get; set; }
    }
}

ShareMusic/Models/Groups/UsersListViewComponentViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShareMusic.Attributes;

namespace ShareMusic.Models.Groups
{
    public class UsersListViewComponentViewModel
    {
        [Display(Name = "Add users to group")]
        public MultiSelectList MultiSelectUsers { get; set; }

        [EnsureOneUserValidation]
        public IEnumerable<string> SelectedUsers { get; set; }
    }
}

ShareMusic/Controllers/GroupsController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ShareMusic.Models.Groups;
using ShareMusic.Services.Interfaces;
using ShareMusic.Extensions;

namespace ShareMusic.Controllers
{
    [Authorize]
    public class GroupsController : Controller
    {
        private readonly IGroupsService groupsService;

        public GroupsController(IGroupsService groupsService)
        {
            this.groupsService = groupsService;
        }

        public IActionResult CreateGroup()
        {
            CreateGroupInputModel viewModel = new CreateGroupInputModel { MultiSelectUsers = this.groupsService.ListAllUsers() };
            return this.View(viewModel);
        }

        [HttpPost]
        public IActionResult CreateGroup(CreateGroupInputModel inputModel) 
        {
            if (!ModelState.IsValid)
            {
                inputModel.MultiSelectUsers = this.groupsService.ListAllUsers();
                return this.View(inputModel);
            }

            inputModel.OwnerId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            this.groupsService.CreateGroup(inputModel);

            return this.Redirect("List");
        }

        public IActionResult List() 
        {
            string userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            GroupsListViewModel viewModel = this.groupsService.ListAllGroupsForUser(userId);
            return this.View(viewModel);
        }

        public IActionResult Search(string searchText)
        {
            GroupsSearchResultViewModel viewModel = this.groupsService.SearchGroups(searchText);
            return this.View(viewModel);
        }

        public IActionResult Details(string id)
        {
            if (id.IsNullOrEmptyOrWhiteSpace())
            {
                return this.RedirectToAction("List");
            }

            string userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            GroupDetailsViewModel groupDetails = this.groupsService.GetGroupDetails(id, userId);
            return this.View(groupDetails);
        }

        [HttpPost]
        public IActionResult Details(UsersListViewComponentViewModel inputModel, string id)
        {
            if (!ModelState.IsValid)
            {
                string userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
                GroupDetailsViewModel groupDetails = this.groupsService.GetGroupDetails(id, userId);
                return this.View(groupDetails);
            }

            this.groupsService.AddUsers(inputModel, id);
            return this.RedirectToAction("List");
        }

        [HttpPost]
        public IActionResult RemoveUser(string username, string groupId)
        {
            if (username.IsNullOrEmptyOrWhiteSpace() || groupId.IsNullOrEmptyOrWhiteSpace())
            {
                return this.RedirectToAction("List");
            }

            this.groupsService.RemoveUser(username, groupId);
            return this.RedirectToAction("Details", new { id = groupId });
        }

        [HttpPost]
        public IActionResult DeleteGroup(string groupName) 
        {
            if (groupName.IsNullOrEmptyOrWhiteSpace())
            {
                return RedirectToAction("List");
            }

            this.groupsService.DeleteGroup(groupName);

            return this.RedirectToAction("List");
        }

        [HttpPost]
        public IActionResult AddSong(string selectedGroup, int songId) 
        {
            if (selectedGroup.IsNullOrEmptyOrWhiteSpace() || songId <= 0)
            {
                return this.Redirect("/");
            }

            string groupId = this.groupsService.AddSong(selectedGroup, songId);
            return this.RedirectToAction("Details", new { id = groupId });
        }

        [HttpPost]
        public IActionResult RemoveSong(int songId, string groupName) 
        {
            if (groupName.IsNullOrEmptyOrWhiteSpace() || songId <= 0)
            {
                return this.RedirectToAction("List");
            }

            string groupId = this.groupsService.RemoveSong(songId, groupName);
            if (string.IsNullOrEmpty(groupId))
            {
                return this.RedirectToAction("List");
            }

            return this.RedirectToAction("Details", new { id = groupId });
        }
    }
}

ShareMusic/Controllers/RequestsController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ShareMusic.Extensions;
using ShareMusic.Models.Requests;
using ShareMusic.Services.Interfaces;

namespace ShareMusic.Controllers
{
    [Authorize]
    public class RequestsController : Controller
    {
        private readonly IRequestsService requestsService;

        public RequestsController(
            IRequestsService requestsService)
        {
            this.requestsService = requestsService;
        }

        [HttpPost]
        public IActionResult Join(string groupId, string userName) 
        {
            if (groupId.IsNullOrEmptyOrWhiteSpace() || userName.IsNullOrEmptyOrWhiteSpace())
            {
                return this.Redirect("/");
            }

            string userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            this.requestsService.Join(groupId, userName, userId);

            return View();
        }

        public IActionResult All(string groupId) 
        {
            if (groupId.IsNullOrEmptyOrWhiteSpace())
            {
                return this.Redirect("/");
            }

            AllGroupRequestsViewModel viewModel = this.requestsService.ListAllReuqestsForGroup(groupId);
            return this.View(viewModel);
        }

        [HttpPost]
        public IActionResult Approve(string groupId, string requestId, string userName) 
        {
            if (groupId.IsNullOrEmptyOrWhiteSpace() || requestId.IsNullOrEmptyOrWhiteSpace() || userName.IsNullOrEmptyOrWhiteSpace())
            {
                return this.RedirectToAction("List", "Groups");
            }

            this.requestsService.ApproveRequest(groupId, requestId, userName);
            return this.RedirectToAction("Details", "Groups", new { id = groupId });
        }

        [HttpPost]
        public IActionResult Decline(string groupId, string requestId, string userName) 
        {
            if (groupId.IsNullOrEmptyOrWhiteSpace() || requestId.IsNullOrEmptyOrWhiteSpace() || userName.IsNullOrEmptyOrWhiteSpace())
            {
                return this.RedirectToAction("List", "Groups");
            }

            this.requestsService.DeclineRequest(groupId, requestId, userName);
            return this.RedirectToAction("All", new { groupId = groupId });
        }
    }
}

ShareMusic/Controllers/SongsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ShareMusic.Common;
using ShareMusic.DataProviders.Interfaces;
using ShareMusic.Models.Songs;
using ShareMusic.Services.Interfaces;
using ShareMusic.Extensions;

namespace ShareMusic.Controllers
{
    public class SongsController : Controller
    {
        private readonly ISongsService songsService;
        private readonly IYoutubeDataProvider youtubeDataProvider;
        private readonly ISongAndArtistNamesSplitterService splitterService;
        private readonly ISongMetadataService metadataService;
        private readonly IGeniusLyricsDataProvider geniusLyrics;

        private readonly ILogger<SongsController> logger;

        public SongsController(
            ISongsService songsService,
            IYoutubeDataProvider youtubeDataProvider,
            ISongAndArtistNamesSplitterService splitterService,
            ISongMetadataService metadataService,
            IGeniusLyricsDataProvider geniusLyrics,
            ILogger<SongsController> logger)
        {
            this.songsService = songsService;
            this.youtubeDataProvider = youtubeDataProvider;
            this.splitterService = splitterService;
            this.metadataService = metadataService;
            this.geniusLyrics = geniusLyrics;
            this.logger = logger;
        }

        [Authorize]
        public IActionResult AddSong()
        {
            AddSongInputModel inputModel = new AddSongInputModel();
            return this.View(inputModel);
        }

        [Authorize]
        [HttpPost]
        public IActionResult AddSong(AddSongInputModel inputModel) 
        {
            if (!ModelState.IsValid)
            {
                return this.View(inputModel);
            }

            List<string> artists = this.splitterService.SplitArtistName(inputModel.Artist).ToList();
            int songId = this.songsService.CreateSong(inputModel.Song, artists);

            string videoId = this.youtubeDataProvider.SearchVideo(string.Join(" ", artists), inputModel.Song);
            if (!string.IsNullOrEmpty(videoId))
            {
                this.metadataService.AddMetadataInfo(songId, GlobalConstants.YouTubeVideo, videoId);
            }
            else
            {
                this.logger.LogWarning($"Video for {string.Join(" ", artists)} {inputModel.Song} not found");
            }

            string lyrics = this.geniusLyrics.AskForLyrics(inputModel.Song, string.Join(" ", artists));
            if (!string.IsNullOrEmpty(lyrics))
            {
                this.metadataService.AddMetadataInfo(songId, GlobalConstants.Lyrics, lyrics);
            }
            else
            {
                this.logger.LogWarning($"Lyrics for {string.Join(" ", artists)} {inputModel.Song} not found");
            }

            this.songsService.UpdateSongsSystemData(songId);

            return this.Redirect("/");
        }

        public IActionResult Details(int songId) 
        {
            if (songId <= 0)
            {
                return this.Redirect("/");
            }

            string userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            SongDetailsViewModel viewModel = this.songsService.GetDetails(songId, userId);
            return this.View(viewModel);
        }

        public IActionResult Search(string searchText) 
        {
            if (searchText.IsNullOrEmptyOrWhiteSpace())
            {
                return this.Redirect("/");
            }

            SongsSearchResultViewModel viewModel = this.songsService.Search(searchText);
            return this.View(viewModel);
        }
    }
}

ShareMusic/ViewComponents/UsersListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using ShareMusic.Models.Groups;
using ShareMusic.Services.Interfaces;

namespace ShareMusic.ViewComponents
{
    [ViewComponent(Name = "UsersList")]
    public class UsersListViewComponent : ViewComponent
    {
        private readonly IGroupsService groupsService;

        public UsersListViewComponent(IGroupsService groupsService)
        {
            this.groupsService = groupsService;
        }

        public IViewComponentResult Invoke()
        {
            UsersListViewComponentViewModel viewModel = new UsersListViewComponentViewModel
            {
                MultiSelectUsers = this.groupsService.ListAllUsers()
            };

            return this.View(viewModel);
        }
    }
}

ShareMusic/Views/Groups/CreateGroup.cshtml
@model CreateGroupInputModel
@{
    ViewData["Title"] = "CreateGroup";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<asp:Content ID="MultiSelectContent" runat="server" ContentPlaceHolderID="MultiSelectContent">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">
</asp:Content>

<div class="row justify-content-center">
    <div class="col-md-6">
        <h1 class="text-center m-md-3">@ViewData["Title"]</h1>
        <section>
            <form asp-controller="Groups" asp-action="CreateGroup" method="post">
                <h4 class="text-center">Add new song to the database.</h4>
                <hr />
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Name"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <vc:users-list></vc:users-list>
                <div class="form-group">
                    <input class="btn btn-success" type="submit" value="Create Group" />
                </div>
            </form>
        </section>
    </div>
</div>

@section Scripts{
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
    <script src="~/js/createGroup.js"></script>
}

ShareMusic/Views/Groups/Details.cshtml
@model GroupDetailsViewModel
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<asp:Content ID="MultiSelectContent" runat="server" ContentPlaceHolderID="MultiSelectContent">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">
</asp:Content>

<div class="row">
    <div class="col-md-8">
        <h1>@Model.Name @ViewData["Title"]</h1>
        <p>Owner name: @Model.OwnerName</p>
    </div>
    @if (Model.OwnerName == this.User.Identity.Name)
    {
        <a class="btn btn-info col-md-2 align-self-center" asp-controller="Requests" asp-action="All" asp-route-groupId="@Model.Id">Group Requests</a>
        <div class="col-md-2 align-self-center">
            <form asp-controller="Groups" asp-action="DeleteGroup" method="post">
                <input type="text" name="groupName" value="@Model.Name" hidden />
                <input onclick="return confirm('Are you sure you want to delete this group?');" class="btn btn-danger text-white" type="submit" value="Delete Group" />
            </form>
        </div>
    }
    @if (!Model.IsUserInGroup)
    {
        <div class="col-md-2 align-self-center">
            <form asp-controller="Requests" asp-action="Join" method="post">
                <input type="text" name="groupId" value="@Model.Id" hidden />
                <input type="text" name="userName" value="@this.User.Identity.Name" hidden />
                <input class="btn btn-success text-white" type="submit" value="Join" />
            </form>
        </div>
    }
</div>

<div class="row">
    <ul class="list-group col-md-12">
        @foreach (var name in Model.GroupUserNames)
        {
            <li class="list-group-item d-md-flex justify-content-between">
                @name
                <div>
                    @if (Model.OwnerName == this.User.Identity.Name)
                    {
                        <form asp-controller="Groups" asp-action="RemoveUser" method="post">
                            <input type="text" name="username" value="@name" hidden />
                            <input type="text" name="groupId" value="@Model.Id" hidden />
                            <input onclick="return confirm('Are you sure you want to remove this user?');" class="btn btn-danger text-white ml-md-2" type="submit" value="Remove User" />
                        </form>
                    }
                </div>
            </li>
        }
    </ul>
    <div class="col-md-7"></div>
    <div class="col-md-5">
        @if (Model.OwnerName == this.User.Identity.Name)
        {
            <form asp-controller="Groups" asp-action="Details" method="post">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="d-md-flex justify-content-between">
                    <vc:users-list></vc:users-list>
                    <div class="form-group">
                        <input class="btn btn-success" type="submit" value="Add" />
                    </div>
                </div>
            </form>
        }
    </div>
</div>

@if (Model.GroupUserNames.Contains(this.User.Identity.Name))
{
    <div class="row">
        <h1 class="text-center">@Model.Name Songs</h1>
        <ul class="list-group col-md-12">
            @foreach (var song in Model.Songs)
            {
                <li class="list-group-item d-md-flex justify-content-between">
                    <a asp-controller="Songs" asp-action="Details" asp-route-songId="@song.SongId">@song.Name</a>
                    <div>
                        @if (Model.OwnerName == this.User.Identity.Name)
                        {
                            <form asp-controller="Groups" asp-action="RemoveSong" method="post">
                                <input type="text" name="songId" value="@song.SongId" hidden />
                                <input type="text" name="groupName" value="@Model.Name" hidden />
                                <input onclick="return confirm('Are you sure you want to remove this song?');" class="btn btn-danger text-white ml-md-2" type="submit" value="Remove Song" />
                            </form>
                        }
                    </div>
                </li>
            }
        </ul>
    </div>
}

@section Scripts{
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
    <script src="~/js/createGroup.js"></script>
}

ShareMusic/Views/Groups/List.cshtml
@model GroupsListViewModel
@{
    ViewData["Title"] = "List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<asp:Content ID="MultiSelectContent" runat="server" ContentPlaceHolderID="MultiSelectContent">
    <link href="~/css/groupSerachForm.css" rel="stylesheet" />
</asp:Content>

<div class="row justify-content-between">
    <div class="col-md-12 row justify-content-center">
        <div class="col-md-8 my-md-4">
            <h2 class="text-center mb-md-2">Search for existing group</h2>
            <form asp-controller="Groups" asp-action="Search" method="get" class="form-inline d-flex justify-content-center md-form form-sm">
                <input asp-for="SearchText" class="form-control form-control-sm mr-3 w-75" placeholder="Search" aria-label="Search" />
                <input type="submit" class="btn btn-outline-info" value="Search" />
            </form>
        </div>
    </div>
    <div class="col-md-6">
        <h3>Groups created by you:</h3>
        <ol>
            @foreach (var group in Model.OwnedGroups)
            {
                <li>
                    <a asp-controller="Groups" asp-action="Details" asp-route-id="@group.Id" class="lead">@group.Name</a>
                </li>
            }
        </ol>
    </div>
    <div class="col-md-6">
        <h3>Groups you take part in:</h3>
        <ol>
            @foreach (var group in Model.GroupsForUser)
            {
                <li>
                    <a asp-controller="Groups" asp-action="Details" asp-route-id="@group.Id" class="lead">@group.Name</a>
                </li>
            }
        </ol>
    </div>
    <div class="col-md-12 row justify-content-center">
        <div class="col-md-6 text-center">
            <h4>Create your own group</h4>
            <a class="btn btn-success" asp-controller="Groups" asp-action="CreateGroup">Create Group</a>
        </div>
    </div>
</div>

ShareMusic/Views/Groups/Search.cshtml
@model GroupsSearchResultViewModel
@{
    ViewData["Title"] = "Search Results";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>@ViewData["Title"] - @Model.Count</h1>

<ul>
    @foreach (var result in Model.SearchResults)
    {
        <li>
            <a asp-controller="Groups" asp-action="Details" asp-route-id="@result.Id">@result.Name</a>
        </li>
    }
</ul>

<form asp-controller="Groups" asp-action="Search" method="get" class="form-inline d-flex justify-content-center md-form form-sm">
    <input asp-for="SearchText" class="form-control form-control-sm mr-3 w-75" placeholder="Search" aria-label="Search" />
    <input type="submit" class="btn btn-outline-info" value="Search" />
</form>